# Generated by Django 2.2.4 on 2019-08-10 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddu_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('add_time', models.DateTimeField()),
                ('release_time', models.DateTimeField()),
                ('log_ip', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ddu_app.UserInfo')),
            ],
            options={
                'db_table': 'user_token',
            },
        ),
    ]
